#if use v1 Compose
#version: '3.8'

services:
  42_dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/app
      - /tmp/.X11-unix:/tmp/.X11-unix			# Share X11 socket
      - $HOME/.Xauthority:/root/.Xauthority:rw	# Share X11 authorization file
      - ~/.ssh:/root/.ssh						# Share ssh key
    environment:
      #- DISPLAY=${DISPLAY}             # Forward the display from the host
      - QT_X11_NO_MITSHM=1             # Prevent potential MIT-SHM errors
      - DISPLAY=host.docker.internal:0
    #network_mode: "host"	# Default network mode : Bridge mode
    ports:
      - "8080:8080"
    container_name: "42_dev"
    stdin_open: true
    tty: true
