services:
  postgresql:
    image: postgres:latest
    #image: sameersbn/postgresql:14-20230628
    container_name: pm_db
    environment:
      - POSTGRES_USER=redmine
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=redmine
      - POSTGRES_NAME=redmine_production
    volumes:
      - type: bind
        source: ${REDMINE_DB_DATA}
        target: /var/lib/postgresql
      #- /srv/docker/redmine/postgresql:/var/lib/postgresql
    healthcheck:
      test: "psql -U postgres"
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 10s
  redmine:
    #build: ./
    image: redmine:latest
    #image: sameersbn/redmine:6.0.3
    container_name: pm_redmine
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - TZ=Asia/Tokyo

      - REDMINE_DB_ADAPTER=postgresql
      - REDMINE_DB_HOST=postgresql
      - REDMINE_DB_PORT=5432
      - REDMINE_DB_USER=redmine
      - REDMINE_DB_PASS=password
      - REDMINE_DB_NAME=redmine_production
      - REDMINE_DB_SSL_MODE=prefer
      - REDMINE_PLUGINS_MIGRATE=1
      #- DB_ADAPTER=postgresql
      #- DB_HOST=postgresql
      #- DB_PORT=5432
      #- DB_USER=redmine
      #- DB_PASS=password
      #- DB_NAME=redmine_production
      #- DB_SSL_MODE=prefer

      - REDMINE_PORT=10083
      - REDMINE_HTTPS=false
      - REDMINE_RELATIVE_URL_ROOT=
      - REDMINE_SECRET_TOKEN=

      - REDMINE_SUDO_MODE_ENABLED=false
      - REDMINE_SUDO_MODE_TIMEOUT=15

      - REDMINE_CONCURRENT_UPLOADS=2

      - REDMINE_BACKUP_SCHEDULE=
      - REDMINE_BACKUP_EXPIRY=
      - REDMINE_BACKUP_TIME=

      - SMTP_ENABLED=false
      - SMTP_METHOD=smtp
      - SMTP_DOMAIN=www.example.com
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=mailer@example.com
      - SMTP_PASS=password
      - SMTP_STARTTLS=true
      - SMTP_AUTHENTICATION=:login

      - IMAP_ENABLED=false
      - IMAP_HOST=imap.gmail.com
      - IMAP_PORT=993
      - IMAP_USER=mailer@example.com
      - IMAP_PASS=password
      - IMAP_SSL=true
      - IMAP_INTERVAL=30

    ports:
      - "10083:80"
    volumes:
      #- /srv/docker/redmine/redmine:/home/redmine/data
      #- /srv/docker/redmine/redmine-logs:/var/log/redmine
      # ssh key
      - type: bind
        source: ./redmine_github_deploy_key
        target: /root/.ssh/id_ed25519

      # ssh config
      - type: bind
        source: ssh/config
        target: /root/.ssh/config

      # Git repository
      - type: bind
        source: ./tmp-repo
        target: /home/redmine/redmine/git-repo # Mount the Git repository

      # Redmine file buckup
      - type: bind
        source: ../pm_redmine_data
        target: /home/redmine/data

      # Redmine file buckup
      - type: bind
        source: ../pm_redmine_logs
        target: /var/log/redmine
